project:
  type: website
  output-dir: docs
  resources:
    - originali/**
    - downloads/**
    - styles.css

website:
  title: "Fusion 2026"
  navbar:
    left:
      - href: index.qmd
        text: Presentazione
      - href: materiali.qmd
        text: Materiali
      - href: controllo.qmd
        text: Controllo contenuti

format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
